# Generated by Django 4.0.3 on 2022-04-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
